services:
  odoo:
    image: odoo:18.0
    container_name: odoo_prod
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=your_strong_password
      - ODOO_MASTER_PASSWORD=your_super_strong_admin_password # Change this!
    restart: always
    init: true

  db:
    image: postgres:15
    container_name: odoo_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=your_strong_password # Must match Odoo's PASSWORD
      - POSTGRES_USER=odoo
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always

volumes:
  odoo-data:
  db-data: